[package]
name = "cairo_v1"
version = "0.3.0"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest

[dependencies]
starknet = ">=1.0.0"
 
[[target.starknet-contract]]

[scripts]
test = "cairo-test --starknet ."
test_single= "cairo-test --starknet . -f"

